CREATE TABLE IF NOT EXISTS userdata (
  id BIGINT PRIMARY KEY,
  money TEXT NOT NULL DEFAULT '5000',
  bank TEXT NOT NULL DEFAULT '0',
  adminuser INTEGER NOT NULL DEFAULT 0,
  blacklist INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS reinforce (
  id BIGINT NOT NULL,
  name TEXT NOT NULL,
  level INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (id, name)
);
